### ISSUE TITLE
Enable drawing

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#32]
- [x] create drawing module
- [x] allow drawing interaction on client
- [ ] create focus area based on drawn feature

<sup>*</sup>Note: OG drawing module built for ol2. This will need to be ol4.

**Comment by rhodges** [comment]
NOTE: As discussed with @mikematecotrustdotorg and @jtutak , drawings are intended to be treatment areas, not 'focus areas'. 
The optimal solution for us is to continue to save the drawing as a Focus Area.
If we wish to handle it as a treatment area (minus land where we have no veg units) we can skip any filtering.
PROBLEM: 
- Results page pulls from 'Scenarios', not 'Focus Areas', so user will see a multipolygon of the veg units that intersect their drawing, not the drawing itself. This will likely be confusing.
SOLUTION OPTIONS:
- Show 'Focus Area' underneath 'Scenario' (filter results). 
   - This gives full transparency to what is happening with their data. 
   - This may confuse 'Select' or 'Filter' users though, whose Focus Areas may be FAR larger than their scenarios.
- Allow 'Draw' users to filter as well
   - Leaves user with understanding of why their scenario is a complex multipolygon, rather than a clean hand-drawn shape
   - Allows ALL users to filter if they wish
