### ISSUE TITLE
Loading reports sometimes does not trigger closing the 'Loading' modal

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ucsrb#45]

**Comment by pollardld** [comment]
Pretty sure this bug is fixed. 

Hide the modal function invocation was moved to top of ajax error function in two cases. The error function was not completing because it was after a knockout observable. Not sure what happened to the KO observable to cause it to fail, as there is no error message. However, the observable is just a place to log the ajax failure so i am not going down that rabbit hole at this time.
